services:
  - type: web
    name: ia-net
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --threads 4 --timeout 120 --keep-alive 5 --log-level info --access-logfile - --error-logfile -
    autoDeploy: true
    healthCheckPath: /ping
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: WEB_CONCURRENCY
        value: 2
